/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#1a5a6a",
        "secondary": "#2a7a8a",
        "on-primary-container": "#003843",
        "on-primary": "#ffffff",
        "surface-bright": "#f7fafb",
        "on-error": "#ffffff",
        "on-surface-variant": "#e0e3e4",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#2e1500",
        "primary-container": "#2e7f91",
        "primary-fixed-dim": "#1e5f71",
        "on-tertiary-fixed-variant": "#6a3b0a",
        "surface-container-low": "rgba(25, 103, 122, 0.4)",
        "on-surface": "#ffffff",
        "primary-fixed": "#0d3f4a",
        "on-background": "#ffffff",
        "tertiary-fixed-dim": "#fdb87d",
        "on-secondary-fixed-variant": "#064e5b",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "inverse-on-surface": "#191c1d",
        "on-primary-fixed-variant": "#004e5d",
        "secondary-fixed": "#b2ecfb",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#cb8d56",
        "surface-container-lowest": "rgba(255, 255, 255, 0.1)",
        "surface-tint": "#14677a",
        "on-tertiary": "#ffffff",
        "surface-container-high": "rgba(255, 255, 255, 0.15)",
        "tertiary": "#fdb87d",
        "on-tertiary-container": "#4f2900",
        "inverse-primary": "#14677a",
        "surface": "#003843",
        "inverse-surface": "#eff1f2",
        "secondary-fixed-dim": "#96cfdf",
        "surface-variant": "rgba(224, 227, 228, 0.1)",
        "secondary-container": "rgba(175, 233, 249, 0.2)",
        "outline-variant": "rgba(191, 200, 204, 0.3)",
        "on-secondary-fixed": "#001f26",
        "on-secondary-container": "#afe9f9",
        "surface-container-highest": "rgba(255, 255, 255, 0.2)",
        "outline": "#8e9192",
        "background": "#002a33",
        "surface-dim": "#001f27",
        "surface-container": "rgba(255, 255, 255, 0.08)",
        "on-primary-fixed": "#001f27",
        "tertiary-fixed": "#ffdcc1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "8px",
        "stack-lg": "32px",
        "gutter": "24px",
        "container-padding-mobile": "16px",
        "container-padding-desktop": "40px",
        "unit": "8px",
        "stack-md": "16px"
      },
      fontFamily: {
        "label-bold": ["Nunito Sans", "sans-serif"],
        "body-md": ["Nunito Sans", "sans-serif"],
        "h1": ["Quicksand", "sans-serif"],
        "body-lg": ["Nunito Sans", "sans-serif"],
        "body-sm": ["Nunito Sans", "sans-serif"],
        "h3": ["Quicksand", "sans-serif"],
        "h2": ["Quicksand", "sans-serif"],
        "h1-mobile": ["Quicksand", "sans-serif"]
      },
      fontSize: {
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "h1": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "h3": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "h2": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "h1-mobile": ["26px", { lineHeight: "34px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
